name: 反馈问题 / Bug Report
description: 反馈错误或异常。 / Report errors or unexpected.
labels: [ Bug ]
title: "[Bug] "
body:
  - type: markdown
    attributes:
      value: |
        为了使我们更好地帮助你，请提供以下信息。

  - type: textarea
    attributes:
      label: 复现步骤 / Steps to reproduce
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    attributes:
      label: 预期行为 / Expected behaviour
    validations:
      required: true

  - type: textarea
    attributes:
      label: 实际行为 / Actual behaviour
    validations:
      required: true

  - type: input
    attributes:
      label: 你的安卓系统版本 / Your Android version
    validations:
      required: true

  - type: input
    attributes:
      label: 应用版本 / App Version
    validations:
      required: true

  - type: textarea
    attributes:
      label: 文件 / Files
      placeholder: 将文件粘贴到此处或者点击文本框底栏上传文件。 / Paste logs here or upload logs by clicking the bar on the bottom.
    validations:
      required: false

  - type: textarea
    id: extra-desc
    attributes:
      label: 补充说明（可选） / Additional information (optional)